### PR TITLE
remove column `original` to avoid bad merge behaviour

### PR DESCRIPTION
**Pull request by nicobonne**
address issue #40

### CODE REVIEW

**Comment by CrohnEngineer** [comment]
Not so sure about removing the 'original' column, as it is needed for creating some splits (like CelebDF).
I would ask before to print the complete error stack trace to find the bug more precisely.

**Comment by nicobonne** [comment]
The `original` column is already present in `df_faces`, so it should be always preserved by the inner merge. If we do not remove it from the fields to preserve, the merge will create two columns, like `original_x` and `original_y` and `df_faces['original']` will result in an error.

**Comment by CrohnEngineer** [comment]
OK!
If the build passes then can we merge it directly?

**Comment by nicobonne** [comment]
yes

**Pull request merged**
